# This is a basic workflow to help you get started with Actions

name: Create new BBC
# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      EVENT_DATE:
        description: 'Date of the event (iso format : `YYYY-mm-dd`)'
        required: true
      NB_MATCH_BYTE_BATTLE:
        description: 'Number of byte battle planned'
        required: true
        default: 1
      NB_PARTICIPANT_BYTE_JAM:
        description: 'Number of participant in the byte jam'
        required: true
        default: 1      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create Byte Battle Casual instance default
        run: |
          python bin/workflows/create_new_bbc.py ${{ github.event.inputs.NB_MATCH_BYTE_BATTLE }} ${{ github.event.inputs.NB_PARTICIPANT_BYTE_JAM }} ${{ github.event.inputs.EVENT_DATE }}

      - name: Configure Git
        run: |
          git config user.name "Publisher"
          git config user.email "publisher@users.noreply.github.com"

      - name: Switch to branch 'gh-pages'
        run: |
          git branch -f ${{ github.event.inputs.EVENT_DATE }}_byte_battle_casuals HEAD
          git checkout -b ${{ github.event.inputs.EVENT_DATE }}_byte_battle_casuals

      - run: |
          git add public/
          git add -A
          git commit -m "Create base ${{ github.event.inputs.EVENT_DATE }} Byte Battle Casuals"
          git push origin ${{ github.event.inputs.EVENT_DATE }}_byte_battle_casuals