# This is a basic workflow to help you get started with Actions

name: Create upcoming PR

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      EVENT_DATE:
        description: 'Date of the event (iso format : `YYYY-mm-dd`)'
        required: true
      EVENT_TITLE:
        description: 'Title of the event'
        required: true
      EVENT_TYPE:
        description: '{"Shader Showdown", "Shader Jam", "Shader Royale", "Byte Battle", "Byte Jam"}'
        required: true
      EVENT_WEBSITE:
        description: '(Optional) Website of the event'
        required: false
      EVENT_CONTACT:
        description: '(Optional) Contact of the event'
        required: false
      EVENT_LOOKING_FOR_PARTICIPANT:
        description: '(Optional, default=false) Is event still looking for participants'
        required: false
      
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          
      - name: Configure Git
        run: |
          git config user.name "Publisher"
          git config user.email "publisher@users.noreply.github.com"

      - name: Update Database
        run: |
          python livecode update
          git add cache/*
          git add public/data/*
          git add public/media/*
          # Only commit and push if there are staged changes.
          git diff --staged --quiet || git commit -m "Update Demozoo handles" && git push origin main

      - name: Switch to branch 'gh-pages'
        run: |
          git branch -f gh-pages HEAD
          git checkout gh-pages

      - name: Generate HTML
        run: python livecode generate

      #- name: Generate Doc
      #  run: |
      #    mkdir -p doc
      #    generate-schema-doc meta/event.schema.json doc/schema.html

      - name: Save commit hash to file
        # Provide a change in case regeneration didn't change any files
        # so upcoming Git commands `add` and `commit` succeed.
        run: git rev-parse --short HEAD > public/commithash.txt

      - run: |
          git add -A
          git commit -m "Publish"
          git push -f origin `git subtree split -P public`:refs/heads/gh-pages
