name: Poster Generator
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config user.name "Publisher"
          git config user.email "publisher@users.noreply.github.com"

      - name: Switch to branch 'gh-pages'
        run: |
          git branch -f posters HEAD
          git checkout posters

      - name: Generate posters
        run: |
          python livecode poster
          git add public/posters/

      - name: Save commit hash to file
        # Provide a change in case regeneration didn't change any files
        # so upcoming Git commands `add` and `commit` succeed.
        run: git rev-parse --short HEAD > public/commithash.txt

      - run: |
          git add -A
          git commit -m "Publish"
          git push -f origin `git subtree split -P public`:refs/heads/posters
